# 맞춤 문제가 만들어지는 과정

모의고사를 푼 뒤 "내 메모에서 만든 문제"가 나오기까지, 시스템이 실제로 무엇을 하는지 단계별로 적은 문서.
아래 예시는 **실제로 생성된 데이터**를 그대로 옮긴 것이다(2026-08-18, demo 계정, gpt-4o-mini).

---

## 0. 한눈에 보기

```
[1] 사용자 응답 수집        판단(매수/매도/관망) + 왜 그랬는지 메모 + 공시 열람 여부
        ↓
[2] 규칙 기반 진단          메모에서 위험 표현을 찾아 행동 패턴으로 분류 (LLM 아님)
        ↓
[3] 출제 우선순위 결정      심각도 → 빈도 순으로 상위 3개 패턴만 출제
        ↓
[4] 대표 근거 선택          그 패턴을 대표할 판단 1개 (틀린 것 우선, 턴 중복 회피)
        ↓
[5] RAG 검색               패턴별 질의로 교육자료 2,381청크에서 근거 3건
        ↓
[6] 프롬프트 조립           사용자의 판단·메모·결과 + 근거 자료 + 출제 규칙
        ↓
[7] LLM 생성               gpt-4o-mini, JSON 강제
        ↓
[8] 형식 검증              보기 4개·정답 인덱스 범위 확인, 실패 시 stub 폴백
        ↓
[9] 저장 + 노출 제어        근거 청크를 함께 고정, 답하기 전엔 정답·해설 숨김
```

핵심 설계는 두 가지다.

- **판정은 규칙, 문장은 LLM.** "이 사람이 어떤 습관을 가졌는가"는 규칙이 정하고, LLM은 그 진단과
  근거 자료를 받아 문장만 만든다. 그래야 왜 이 문제가 나왔는지 항상 설명할 수 있다.
- **문제는 반드시 실제 자료에서 나온다.** LLM에게 자유롭게 문제를 만들게 하지 않고, 벡터 검색으로
  찾은 청크를 프롬프트에 넣고 "이 내용에만 근거하라"고 지시한 뒤, 어느 청크였는지를 DB에 남긴다.

---

## [1] 사용자 응답 수집

한 턴마다 세 가지를 받는다. 이 중 **메모가 이 시스템의 원재료**다.

| 항목 | 예시 | 쓰이는 곳 |
|---|---|---|
| `action` | `BUY` | 모범답안과 비교 → 정답/오답 |
| `reasonMemo` | "실검 1위에 다들 사는 분위기라 그냥 느낌이 좋았어요" | **진단의 입력** |
| `viewedDisclosure` | `false` | 공시 미확인 진단 |

메모는 10자 이상 필수다(`ExamService.minMemoLength`). 비워두면 진단이 단순 매매 통계로 떨어져서
"내 메모를 읽고 만든 문제"라는 차별점이 사라진다.

> 매매 기록만 보면 "1턴에 매수했다"까지만 알 수 있다. 메모가 있어야 같은 매수라도
> **리딩방을 보고 샀는지 / 평단가를 낮추려고 샀는지**를 구분해 다른 처방을 줄 수 있다.

---

## [2] 규칙 기반 진단

`ExamDiagnosisRules.diagnose()`가 응답 전체를 훑으며 **표현 + 행동** 조합으로 패턴을 찾는다.
LLM을 쓰지 않는 이유는 (a) 왜 그렇게 판단했는지 항상 설명할 수 있어야 하고, (b) 같은 입력에
같은 결과가 나와야 재도전 전후 비교가 의미를 갖기 때문이다.

| 패턴 | 감지 표현 | 해당 행동 |
|---|---|---|
| `NEWS_CHASING` | 리딩방, 추천, 마지막 기회, 지금 아니면, 실검, 수혜주, 테마 | 매수 |
| `HERD_FOLLOWING` | 다들, 남들, 분위기, 뒤처, 인증, 1위, 너도나도 | 매수 |
| `PANIC_SELL` | 무서, 불안, 더 떨어질, 겁, 폭락, 던지 | 매도 |
| `LOSS_AVERSION` | 평단, 물타기, 추가매수, 버티, 손실이 확정, 본전 | 매수·관망 |
| `NO_RATIONALE` | 느낌, 감으로, 그냥, 왠지, 찍, 몰라 | 전부 |
| `DISCLOSURE_IGNORED` | (표현이 아니라) **매수의 50% 이상에서 공시 미열람** | 매수 |

심각도는 **틀린 판단의 개수**로 매긴다 — 2회 이상 `HIGH`, 1회 `MEDIUM`, 0회 `LOW`.
맞은 판단에서도 표현이 잡히면 근거에는 남지만 심각도를 올리지는 않는다.

### 실제 진단 결과 (DB `exam_diagnoses`)

```
pattern_key : HERD_FOLLOWING
severity    : HIGH        (틀린 판단 2회)
hit_count   : 3
rag_query   : 군중심리에 휩쓸린 투자와 과열된 테마주의 위험
evidence    : [
  { turnNo: 1, stockName: "종목 A", action: "BUY",  wasWrong: true,
    matched: ["다들", "분위기"],
    memo: "리딩방에서 마지막 기회라고 하고 다들 사는 분위기라 저도 샀어요",
    outcomeChangePct: -42.0 },
  { turnNo: 4, stockName: "종목 D", action: "BUY",  wasWrong: true,
    matched: ["다들", "분위기", "1위"],
    memo: "실검 1위에 다들 사는 분위기라 그냥 느낌이 좋았어요",
    outcomeChangePct: -62.66 },
  { turnNo: 5, stockName: "종목 E", action: "BUY",  wasWrong: false,
    matched: ["분위기"],
    memo: "공시를 보니 매출이 늘고 자사주도 산다고 해서 숫자가 분위기와 달랐어요",
    outcomeChangePct: 36.36 }
]
```

`evidence`에 **어떤 표현 때문에 잡혔는지(matched)와 원문 메모**를 그대로 남기는 게 중요하다.
이 값이 그대로 화면의 "감지: 다들, 분위기"와 LLM 프롬프트에 들어간다.

---

## [3] 출제 우선순위

진단이 6개 나와도 문제는 3개만 만든다. 다 내면 학습이 아니라 시험이 되고, LLM 호출 비용도 늘어난다.

정렬 기준은 **심각도 → 빈도**다.

```
[HIGH]   남들 따라 사기(군중심리)    3회   ← 출제
[HIGH]   공시 확인 없이 판단         3회   ← 출제
[HIGH]   뉴스·리딩방 보고 추격매수   2회   ← 출제
[MEDIUM] 공포에 매도                1회   (제외)
[MEDIUM] 손실 확정 회피·물타기       1회   (제외)
[MEDIUM] 근거 없는 판단             1회   (제외)
```

---

## [4] 대표 근거 선택

한 패턴에 여러 판단이 걸리므로 그중 **하나**를 골라 문제의 소재로 쓴다(`pickEvidence`).

우선순위:
1. **앞 문제에서 이미 인용한 턴은 피한다** — 3문제가 전부 같은 턴을 인용하면 "내 모의고사를 읽고
   만든 문제"로 느껴지지 않는다. 실제로 초기 버전이 이 문제를 겪어서 넣은 규칙이다.
2. **틀린 판단 우선** — 맞은 판단보다 배울 게 많다.
3. **손익 영향이 큰 순** — 같은 조건이면 -62%가 -42%보다 강한 교훈이다.

위 예시에서는 1턴(-42%)과 4턴(-62.66%) 중 **4턴**이 선택됐다.

---

## [5] RAG 검색 — 근거 자료 찾기

패턴마다 미리 정의된 자연어 질의(`ragQuery`)로 교육자료를 검색한다. 스탯 코드(`HERD_FOLLOWING`)를
그대로 검색하면 아무것도 안 걸리므로, 그 패턴이 뜻하는 개념을 문장으로 풀어 쓴 것이다.

```
질의: "군중심리에 휩쓸린 투자와 과열된 테마주의 위험"
  ↓ bge-m3로 1024차원 벡터 변환 (파이썬 검색 서버, JVM에서 못 돌려서 HTTP 분리)
  ↓ pgvector 코사인 유사도 (edu_chunks 2,381개, HNSW 인덱스)
  ↓ 유사도 0.5 미만은 버림 — 무관한 자료가 근거인 척 붙는 걸 막기 위함
```

### 실제 검색 결과 (93.8ms)

```
[자료1] 0.5505 · 대학생을 위한 실용금융(제4판) 543쪽
   "…신규 투자자의 저조한 투자 성과는 잦은 거래와 밀접한 관련이 있다는 분석이다.
    거래회전율, 일중거래비중, 종목교체율이 높을수록 일간 초과수익률이 낮았다…"
[자료2] 0.5348 · 대학생을 위한 금융 첫걸음 123쪽
   "…'묻지마 투자'라는 표현처럼, 소비자가 스스로의 금융적 판단 책임을 회피하게…"
[자료3] 0.5331 · 대학생을 위한 실용금융(제4판) 486쪽
   "…기대수익률과 위험의 상충관계…"
```

3건 모두 프롬프트에 들어가고, **1위 자료가 그 문제의 출처로 DB에 기록**된다.

---

## [6] 프롬프트 조립

`ExamQuizPrompt.build()`가 만드는 실제 프롬프트 구조:

```
당신은 투자 교육 코치입니다. 아래 사용자의 실제 모의고사 판단을 보고,
제공된 교육자료에 근거해서 4지선다 문제 1개를 만들어주세요.

[사용자의 판단]
- 4턴 종목 D에서 'BUY'를 선택
- 그 이유로 이렇게 적었습니다: "실검 1위에 다들 사는 분위기라 그냥 느낌이 좋았어요"
- 결과: 이후 -62.66%
- 진단된 습관: 남들 따라 사기(군중심리)

[교육자료 — 반드시 이 내용에만 근거할 것]
[자료 1] 대학생을 위한 실용금융 (제4판) · 금융감독원 543쪽
…신규 투자자의 저조한 투자 성과는 잦은 거래와… (각 700자로 자름)
[자료 2] …
[자료 3] …

[요구사항]
1. 정답은 반드시 하나만 성립해야 한다. 나머지 3개 보기는 명백히 틀린 내용으로 쓸 것.
2. 오답 보기도 그럴듯해야 하지만, 자세히 보면 왜 틀렸는지 분명해야 한다.
3. why_this_question에는 위 메모를 직접 인용해서 쓸 것.
   예: 4턴에서 "실검 1위에 다들 사는 분…"라고 적으셨죠. 그 판단의 근거를 다시 살펴보는 문제예요.
4. 자연스러운 한국어로 쓸 것. 사전에 없는 조어를 만들지 말 것.
5. 자료에 없는 내용을 지어내지 말 것.
6. 아래 JSON 형식으로만 답할 것. <> 안은 설명이니 그대로 옮겨 적지 말 것.

{"question":"<질문 한 문장>","options":["<보기1>",…],"correct_index":<0~3>,
 "explanation":"<자료를 근거로 2~3문장>","why_this_question":"<3번 형식대로>"}
```

요구사항이 이렇게 구체적인 이유는 전부 **실제로 겪은 실패** 때문이다.

| 요구사항 | 넣기 전에 생긴 일 |
|---|---|
| 1번 (정답 하나만) | 정답이 두 개 성립하는 문제가 나와 문제로 성립하지 않았음 |
| 3번 (메모 인용) | "이 사용자에게 도움이 되기 때문"처럼 일반론만 써서 개인화가 사라짐 |
| 4번 (조어 금지) | "밀실적 판단 능력" 같은 사전에 없는 말이 보기에 등장 |
| 6번 (`<>` 설명) | JSON 템플릿의 설명 문구를 값으로 그대로 복사해 넣음 |

---

## [7] LLM 생성

- 모델: `gpt-4o-mini` (설정으로 교체 가능)
- `response_format: {"type":"json_object"}` — JSON 강제로 파싱 실패를 줄인다
- system 메시지로 "제공된 자료에만 근거, JSON으로만 답변"을 한 번 더 못박는다
- 문제 1개당 입력 약 1,700 토큰 / 출력 약 200~250 토큰 → **응시 1회(3문제) 약 1.6원**

키가 없으면 `StubExamQuizGenerator`가 패턴별 고정 문항을 돌려준다. 문항은 고정이지만
근거 자료 연결과 저장 경로는 LLM 경로와 완전히 같아서, **키 없이도 데모가 끊기지 않는다.**

---

## [8] 형식 검증

`ExamQuizPrompt.parse()`가 응답에서 `{`…`}` 구간만 잘라 파싱한 뒤 검사한다.

- 질문·해설이 비어 있지 않은가
- 보기가 정확히 4개이고 빈 문자열이 없는가
- `correct_index`가 0~3 범위인가

하나라도 어긋나면 그 문제는 버리고 stub으로 대체한다.

> **한계**: 이건 형식 검증일 뿐이다. "정답이 두 개 성립하는가", "자료에 없는 내용을 지어냈는가"
> 같은 **내용 검증은 못 한다.** 프롬프트로 최대한 막고 있지만 최종 확인은 사람이 해야 하고,
> 문항을 대량 생성할 계획이면 검수 화면이나 2차 LLM 검증이 필요하다.

---

## [9] 저장과 노출 제어

`exam_quiz_questions` 한 행에 문제와 **출처가 함께** 들어간다.

```
position          : 0
pattern_key       : HERD_FOLLOWING          ← 어떤 진단에서 나왔는지
related_turn_no   : 4                       ← 어떤 판단이 계기였는지
question          : 투자자가 남들 따라 사기(군중심리)에 빠졌을 경우 발생할 수 있는 문제는 무엇인가요?
explanation       : 군중심리에 따라 투자 결정을 하는 경우, 분석이나 정보를 무시하고 타인의 행동에
                    의존하게 되어 손실을 볼 가능성이 높아집니다. 이는 '잦은 거래와 밀접한 관련이
                    있다'는 분석과 일치합니다.
why_this_question : 4턴에서 '실검 1위에 다들 사는 분위기라 그냥…'라고 적으셨죠.
                    그 판단의 근거를 다시 살펴보는 문제예요.
source_title      : 대학생을 위한 실용금융 (제4판)
source_page_start : 543
source_page_end   : 544
source_score      : 0.55

보기 (exam_quiz_options)
  0. 자신의 분석에 기반하여 합리적인 판단을 내린다.
  1. 소속감 때문에 위험을 무시하고 투자하게 된다.        ← 정답
  2. 정확한 정보를 바탕으로 신중한 결정을 하게 된다.
  3. 투자 성과가 향상된다.
```

출처를 문제와 같은 행에 박아두는 이유는 **할루시네이션 방어**다. "이 문제는 금감원 실용금융
543–544쪽에서 나왔다"를 확정적으로 보여줄 수 있어야, 심사에서 "AI가 지어낸 것 아니냐"에 답할 수 있다.

### 정답 유출 방지

퀴즈 조회 API는 답하기 전까지 `correctOptionId`·`explanation`·`whyThisQuestion`을 **null로 내려준다**.
프론트가 조심하는 데 기대지 않고 서버에서 아예 빼는 방식이라, 응답 JSON을 열어봐도 정답을 알 수 없다.

```
안 푼 문제 →  answered: false · correctOptionId: null · explanation: null
푼 문제   →  answered: true  · correctOptionId: "…"  · explanation: "…"
```

---

## 재생성과 멱등성

같은 응시로 다시 만들면 이전 세트를 지우고 새로 만든다. 이때 두 가지를 지켜야 한다.

1. **삭제 순서**: 보기 → 문항 → 세트. FK에 `ON DELETE CASCADE`가 없어서 순서를 어기면 위반이 난다.
2. **flush 시점**: Hibernate는 한 트랜잭션에서 INSERT를 DELETE보다 **먼저** 내보낸다. 명시적으로
   flush하지 않으면 지우기 전에 같은 키가 들어가 유니크 제약을 위반한다. (둘 다 실제로 터진 버그다.)

프론트는 이미 만들어둔 세트가 있으면 그걸 재사용해서 불필요한 LLM 호출을 막는다.

---

## 관련 코드

| 단계 | 파일 |
|---|---|
| 진단 규칙 | `backend/…/service/ExamDiagnosisRules.kt` |
| 전체 흐름 | `backend/…/service/ExamQuizService.kt` |
| 프롬프트·파싱·검증 | `backend/…/service/ai/ExamQuizGenerator.kt` |
| OpenAI 호출 | `backend/…/service/ai/OpenAiExamQuizGenerator.kt` |
| 키 없을 때 폴백 | `backend/…/service/ai/StubExamQuizGenerator.kt` |
| 벡터 검색 서버 | `edu-rag-indexer/web_search.py` |
| 파이썬 프로토타입 | `mock-exam/quizgen.py` (같은 로직, 배치 실행용) |

지식베이스(edu_chunks 2,381개)가 어떻게 만들어졌는지는
[edu-rag-indexer/PIPELINE.md](../edu-rag-indexer/PIPELINE.md) 참고.
